model_name_or_path: /root/autodl-tmp/demo3/llama/models/Qwen2.5-0.5B-Instruct
adapter_name_or_path: /root/autodl-tmp/demo3/llama/outputs/identity_lora_full
template: qwen
finetuning_type: lora
infer_backend: huggingface